### PR TITLE
Selectively skip replacements via custom attribute

### PR DESCRIPTION
**Pull request by Konamiman**
If a class method or property is decorated with an attribute named `SkipStaticReplacementsAttribute`, then no static replacements will be performed in that member. If the attribute is applied on a type, replacements are entirely skipped for the whole type.

This is useful if you want to define a delegate-based replacement class that defaults to invoking the original static members:

```
[StaticReplacement(typeof(DateTime))]
[SkipStaticReplacements]
public static class DateTime_Replacement
{
    static DateTime_Replacement()
    {
        Now_Replacement = () => DateTime.Now;
    }

    public static Func<DateTime> Now_Replacement { get; set; }

    public static DateTime Now
    {
        get { return Now_Replacement(); }
    }
}
```

Known issues:
- Unit tests throw BadImageFormatException if `SkipStaticReplacementsAttribute` is defined in the portable assembly included in the solution, no idea why.
- The "approved tests" fail, but the file differences shown seem to be trivial.

### CODE REVIEW

**Comment by dallinbeutler** [comment]
Is there a way you could make your fork public? This is exactly what I need!

**Comment by dallinbeutler** [comment]
@SimonCropp I'm fairly new to Fody, and don't have @Konamiman 's repo but I'll try my best!

 I was thinking to maybe just adjust the logic so it just ignores methods inside a class with the [StaticReplacement()] attribute. Since the methods are overwriting the original static class anyway, we would then have access to calling the new functions internally, or the ignored original class if we need to. 

It could also be made as a flag passed in the StaticReplacement constructor if we want the option.

 What would you prefer?

**Comment by SimonCropp** [comment]
sorry for dropping this. do u still need it?

**Comment by dallinbeutler** [comment]
> sorry for dropping this. do u still need it?

Go ahead and close it

**Pull request closed without merging**
